apiVersion: v2
name: lumina
version: 0.1.0
appVersion: "main"
description: Lumina - Kubernetes Cost Visibility Controller
type: application
keywords:
  - kubernetes
  - cost
  - aws
  - savings-plans
  - visibility
home: https://github.com/Nextdoor/lumina
sources:
  - https://github.com/Nextdoor/lumina
maintainers:
  - name: Lumina Maintainers
    url: https://github.com/Nextdoor/lumina
